### ISSUE TITLE
Vercel Deployment Problem

### ISSUE THREAD

**Issue by QuantMallah** [BhargavaTejaN/cloud-file-manager#1]
Bro, How did you deploy on Vercel It's creating Error 

"Server error There is a problem with the server configuration.
Check the server logs for more information."

**Comment by QuantMallah** [comment]
![image](https://github.com/BhargavaTejaN/cloud-file-manager/assets/106310821/771452d5-429f-443d-b820-cc60f2aba727)
The moment I run npm run dev this error is coming on my local host

**Comment by QuantMallah** [comment]
![image](https://github.com/BhargavaTejaN/cloud-file-manager/assets/106310821/5ff5f85b-498e-4186-8cbb-22005a23875c)
Can you Help me Out Please running this Project

**Comment by QuantMallah** [comment]
![image](https://github.com/BhargavaTejaN/cloud-file-manager/assets/106310821/266a2936-1334-4038-a2dd-472411c504c7)
Can you mention the Steps of Deploying the Project on Vercel
Did you Set any Environment Variables or Build and Output Settings?
Please Help Me Out!

**Comment by BhargavaTejaN** [comment]
you don't have .env file in your project.
In that .env file you need to mention your client id

May be due to that you are getting error bro please check whether u included the client id and client screet key of your google account

**Comment by QuantMallah** [comment]
![image](https://github.com/BhargavaTejaN/cloud-file-manager/assets/106310821/6c0427ca-61f2-4cf2-871f-e7a353b0be6f)
Can you mention the Steps of Deploying the Project on Vercel
Did you Set any Environment Variables or Build and Output Settings?
Please Help Me Out!

**Comment by QuantMallah** [comment]
> > ![image](https://user-images.githubusercontent.com/106310821/279383995-266a2936-1334-4038-a2dd-472411c504c7.png) Can you mention the Steps of Deploying the Project on Vercel Did you Set any Environment Variables or Build and Output Settings? Please Help Me Out!
> 
> Yes u need to import env variables if u have in u r project or else it won't work

How Should I Set Up Environment Variables?!

**Comment by BhargavaTejaN** [comment]
> > > ![image](https://user-images.githubusercontent.com/106310821/279383995-266a2936-1334-4038-a2dd-472411c504c7.png) Can you mention the Steps of Deploying the Project on Vercel Did you Set any Environment Variables or Build and Output Settings? Please Help Me Out!
> > 
> > 
> > Yes u need to import env variables if u have in u r project or else it won't work
> 
> How Should I Set Up Environment Variables?!

At the bottom you can see environment variables.. In that copy your entire env variables and paste it.. It will auto matically add env variables accordingly...

**Comment by QuantMallah** [comment]
> > > > ![image](https://user-images.githubusercontent.com/106310821/279383995-266a2936-1334-4038-a2dd-472411c504c7.png) Can you mention the Steps of Deploying the Project on Vercel Did you Set any Environment Variables or Build and Output Settings? Please Help Me Out!
> > > 
> > > 
> > > Yes u need to import env variables if u have in u r project or else it won't work
> > 
> > 
> > How Should I Set Up Environment Variables?!
> 
> At the bottom you can see environment variables.. In that copy your entire env variables and paste it.. It will auto matically add env variables accordingly...

I'm not getting how should I set up environment variables

**Comment by BhargavaTejaN** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/106310821/279383995-266a2936-1334-4038-a2dd-472411c504c7.png) Can you mention the Steps of Deploying the Project on Vercel Did you Set any Environment Variables or Build and Output Settings? Please Help Me Out!
> > > > 
> > > > 
> > > > Yes u need to import env variables if u have in u r project or else it won't work
> > > 
> > > 
> > > How Should I Set Up Environment Variables?!
> > 
> > 
> > At the bottom you can see environment variables.. In that copy your entire env variables and paste it.. It will auto matically add env variables accordingly...
> 
> I'm not getting how should I set up environment variables

Bro before deolying is u t project working fine in local environment?

**Comment by QuantMallah** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/106310821/279383995-266a2936-1334-4038-a2dd-472411c504c7.png) Can you mention the Steps of Deploying the Project on Vercel Did you Set any Environment Variables or Build and Output Settings? Please Help Me Out!
> > > > > 
> > > > > 
> > > > > Yes u need to import env variables if u have in u r project or else it won't work
> > > > 
> > > > 
> > > > How Should I Set Up Environment Variables?!
> > > 
> > > 
> > > At the bottom you can see environment variables.. In that copy your entire env variables and paste it.. It will auto matically add env variables accordingly...
> > 
> > 
> > I'm not getting how should I set up environment variables
> 
> Bro before deolying is u t project working fine in local environment?

I Got it bro I followed the Video I have to Create Env Secret File!
Let's see if it works! Just help me in case If any problem stay in touch!

**Comment by BhargavaTejaN** [comment]
> you don't have .env file in your project. In that .env file you need to mention your client id
> 
> May be due to that you are getting error bro please check whether u included the client id and client screet key of your google account

Here itself i told u don't have env file in u r project u need to check my complete message...

**Comment by BhargavaTejaN** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/106310821/279383995-266a2936-1334-4038-a2dd-472411c504c7.png) Can you mention the Steps of Deploying the Project on Vercel Did you Set any Environment Variables or Build and Output Settings? Please Help Me Out!
> > > > > > 
> > > > > > 
> > > > > > Yes u need to import env variables if u have in u r project or else it won't work
> > > > > 
> > > > > 
> > > > > How Should I Set Up Environment Variables?!
> > > > 
> > > > 
> > > > At the bottom you can see environment variables.. In that copy your entire env variables and paste it.. It will auto matically add env variables accordingly...
> > > 
> > > 
> > > I'm not getting how should I set up environment variables
> > 
> > 
> > Bro before deolying is u t project working fine in local environment?
> 
> I Got it bro I followed the Video I have to Create Env Secret File! Let's see if it works! Just help me in case If any problem stay in touch!

Bro i already told u don't have env file i think u didn't check that message... Please read all messages carefully

**Comment by QuantMallah** [comment]
Hey bro Please delete all the Issues you only have control over that I can't 
my problem is solved it's working now
delete all issues

**Comment by BhargavaTejaN** [comment]
> Hey bro Please delete all the Issues you only have control over that I can't my problem is solved it's working now delete all issues

Hey bro want to connect with you how can i connect?

**Comment by QuantMallah** [comment]
This is my WhatsApp No. 9769398946

**Comment by QuantMallah** [comment]
Even I want to Discuss!

**Comment by QuantMallah** [comment]
hi
